Week_4_Django/14-Django/currycrown/currycrown/urls.py
# from django.contrib import views as auth_views
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from . import views
from debug_toolbar.toolbar import debug_toolbar_urls
from django.shortcuts import redirect

urlpatterns = [
    path("admin/", admin.site.urls),
    path("logout", views.user_logout, name="logout"),
    path("management/", include("management.urls")),
    path("customer/", include("customer.urls")),
    path("register/", views.register, name="register_user"),
    path("login/", views.user_login, name="login"),
    path("", views.about, name="landing_page"),
    re_path(r"^.*$", lambda request: redirect("landing_page")),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Week_4_Django/14-Django/currycrown/customer/urls.py
from django.urls import path
from . import views

app_name = "customer"

urlpatterns = [
    path("view/", views.view_menu, name="view_menu"),
    path("place_order/", views.place_order, name="place_order"),
    path(
        "order_confirmation/<int:order_id>/",
        views.order_confirmation,
        name="order_confirmation",
    ),
    path("show_order/<int:user_id>/", views.view_orders, name="show_orders"),
]

Week_4_Django/14-Django/currycrown/management/urls.py
from django.urls import path
from . import views

app_name = "management"  

urlpatterns = []

menu_task = [
    path("add/", views.add_menu_item, name="add_menu_item"),
    path("view/", views.view_menu, name="view_menu"),
    path("specificmenu/", views.specific_view_menu, name="specific_view_menu"),
    path("remove/<int:item_id>/", views.remove_menu_item, name="remove_menu_item"),
    path("update/<int:item_id>/", views.update_menu, name="update_menu"),
]

order_task = [
    path("order/", views.show_orders, name="show_orders"),
    path("order/approve/<int:order_id>/", views.approve_order, name="approve_order"),
]
urlpatterns = urlpatterns + menu_task + order_task

Week_4_Django/14-Django/currycrown/management/models.py
from django.db import models


class Menu(models.Model):
    """Menu Model"""

    item_id = models.AutoField(primary_key=True)
    item_name = models.CharField(max_length=100)
    item_image = models.ImageField(upload_to="image")
    item_desc = models.TextField()
    item_price = models.PositiveBigIntegerField()
    item_rating = models.IntegerField(choices=[(i, i) for i in range(1, 6)], default=1)

    def __str__(self):
        return self.item_name

Week_4_Django/14-Django/currycrown/management/forms.py
"""Include neccessary imports"""

from django import forms
from .models import Menu
from django.core.exceptions import ValidationError


class MenuForm(forms.ModelForm):
    """Class to create menu form"""

    class Meta:
        """This defines the form's layout"""

        model = Menu
        fields = ["item_name", "item_price", "item_desc", "item_rating", "item_image"]

    def clean_item_name(self):
        item_name = self.cleaned_data.get("item_name")
        if Menu.objects.filter(item_name=item_name).exists():
            raise ValidationError("Menu Item Exists")
        return item_name

    def clean_item_image(self):
        limit = 5 * 1024 * 1024
        item_image = self.cleaned_data.get("item_image")
        print(item_image.size)

        if item_image:
            if item_image.size > limit:
                raise ValidationError("Image size should not exceed 5MB.")

            if not item_image.name.endswith(("jpg", "png", "jpeg")):
                raise ValidationError(
                    "Invalid Image Format. Only jpg and png are allowed."
                )

        return item_image


class UpdateMenuForm(MenuForm):

    def clean_item_name(self):
        item_name = self.cleaned_data.get("item_name")
        return item_name.title()

Week_4_Django/14-Django/currycrown/management/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.db.models import Q
from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render
from customer.models import Orders
from .models import Menu
from .forms import MenuForm, UpdateMenuForm


@login_required(login_url="/login")
@staff_member_required
def add_menu_item(request):
    """This view is to add any dish item"""
    if request.method == "POST":
        form = MenuForm(request.POST, request.FILES)
        if form.is_valid():
            form.save()
            return redirect("management:view_menu")
    else:
        form = MenuForm()

    return render(request, "management/add_menu_item.html", {"form": form})


@login_required(login_url="/login")
@staff_member_required
def view_menu(request):
    """This is to view the whole menu"""
    menu_items = Menu.objects.all()
    paginator = Paginator(menu_items, 5)
    page = request.GET.get("page")

    try:
        items = paginator.page(page)
    except PageNotAnInteger:
        items = paginator.page(1)
    except EmptyPage:
        items = paginator.page(paginator.num_pages)

    return render(request, "management/view_menu.html", {"menu_items": items})


@login_required(login_url="/login")
@staff_member_required
def specific_view_menu(request):
    """This is to view specific menu"""
    q = Q(item_price__gt=500) | Q(item_name__contains="a")
    menu_items = Menu.objects.filter(q)
    return render(request, "management/view_menu.html", {"menu_items": menu_items})


@login_required(login_url="/login")
@staff_member_required
def update_menu(request, item_id):
    """This is to update the menu item"""

    menu_item = get_object_or_404(Menu, item_id=item_id)
    form = UpdateMenuForm(instance=menu_item)
    if request.method == "POST":
        form = UpdateMenuForm(request.POST, request.FILES, instance=menu_item)
        if form.is_valid():
            form.save()
            return redirect("management:view_menu")
    return render(request, "management/add_menu_item.html", {"form": form})


@login_required(login_url="/login")
@staff_member_required
def remove_menu_item(request, item_id):
    """This view is to remove any added menu item"""

    item = get_object_or_404(Menu, item_id=item_id)

    if request.method == "POST":
        item.delete()
        messages.info(request, "The item has been deleted successfully!")
        return redirect("management:view_menu")

    return render(request, "management/remove_menu_item.html", {"item": item})


@login_required(login_url="/login")
@staff_member_required
def show_orders(request):
    """This is to show all the orders of the user"""

    orders = Orders.objects.select_related("user").all().order_by("-order_time")
    if request.method == "POST":
        specific_orders = request.POST.get("specific", "")
        if specific_orders:
            orders = (
                Orders.objects.select_related("user")
                .filter(order_status=specific_orders)
                .order_by("-order_time")
            )
        else:
            orders = Orders.objects.select_related("user").all()
    return render(request, "management/show_orders.html", {"orders": orders})


@login_required(login_url="/login")
@staff_member_required
def approve_order(request, order_id):
    """This is to approve order to approve"""

    myorder = Orders.objects.get(order_id=order_id)
    if request.method == "POST":
        updated_status = request.POST["Updated status"]
        myorder.order_status = updated_status
        messages.info(request, "The order status has been changed successfully!")
        myorder.save()

    return render(request, "management/approve_order.html", {"order": myorder})

Week_4_Django/14-Django/currycrown/management/templates/management/add_menu_item.html
{% extends 'base.html' %}

{% block title %}Add/Update Menu Item{% endblock %}

{% block content %}
    <div class="content-container">
        <h1 style="text-align: center; margin-bottom: 3%; font-size: 400%;">Menu Item</h1>
        
        <div class="form-container" style="max-width: 600px; margin: 0 auto; padding: 20px; background-color: #f9f9f9; border-radius: 8px; box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                
                <!-- Item Name Field -->
                <div class="form-field">
                    <label for="item_name" style="font-weight: bold;">Item Name:</label>
                    {{ form.item_name }}
                    {% if form.item_name.errors %}
                        <div class="error-message" style="color: red; font-size: 14px; margin-top: 5px;">
                            {% for error in form.item_name.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <!-- Item Price Field -->
                <div class="form-field">
                    <label for="item_price" style="font-weight: bold;">Item Price:</label>
                    {{ form.item_price }}
                    {% if form.item_price.errors %}
                        <div class="error-message" style="color: red; font-size: 14px; margin-top: 5px;">
                            {% for error in form.item_price.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                
                <!-- Item Description Field -->
                <div class="form-field">
                    <label for="item_desc" style="font-weight: bold;">Item Description:</label>
                    <textarea name="item_desc" id="item_desc" rows="4" style="width: 100%; padding: 10px; border-radius: 5px; border: 1px solid #ddd; font-size: 16px; margin: 10px 0;">{% if form.item_desc.value %}{{ form.item_desc.value }}{% else %}{% endif %}</textarea>
                    {% if form.item_desc.errors %}
                        <div class="error-message" style="color: red; font-size: 14px; margin-top: 5px;">
                            {% for error in form.item_desc.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <!-- Item Rating Field -->
                <div class="form-field">
                    <label for="item_rating" style="font-weight: bold;">Item Rating:</label>
                    {{ form.item_rating }}
                    {% if form.item_rating.errors %}
                        <div class="error-message" style="color: red; font-size: 14px; margin-top: 5px;">
                            {% for error in form.item_rating.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>
                
                <!-- Item Image Field -->
                <div class="form-field">
                    <label for="item_image" style="font-weight: bold;">Item Image:</label>
                    {{ form.item_image }}
                    {% if form.item_image.errors %}
                        <div class="error-message" style="color: red; font-size: 14px; margin-top: 5px;">
                            {% for error in form.item_image.errors %}
                                <p>{{ error }}</p>
                            {% endfor %}
                        </div>
                    {% endif %}
                </div>

                <div class="button-container" style="text-align: center;">
                    <button type="submit" class="submit-button">Add Item</button>
                </div>
            </form>
        </div>

        <br>
        <div style="text-align: center; margin-bottom: 3%;">
            <a href="{% url 'management:view_menu' %}" style="text-decoration: none; color: #909a05; font-size: 16px; font-weight: bold; transition: color 0.3s;">
                Back to Menu
            </a>
        </div>
    </div>
{% endblock %}

{% block styles %}
<style>
    .submit-button {
        padding: 10px 55px;
        background-color: #ffbe33;
        color: white;
        border-radius: 45px;
        text-transform: uppercase;
        font-size: 16px;
        border: none;
        cursor: pointer;
        transition: background-color 0.3s;
    }

    .submit-button:hover {
        background-color: #e69c00;
    }

    .form-container input,
    .form-container select,
    .form-container textarea {
        width: 100%;
        padding: 10px;
        margin: 10px 0;
        border-radius: 5px;
        border: 1px solid #ddd;
        font-size: 16px;
    }

    .form-container input[type="file"] {
        border: none;
    }

    .form-container select {
        background-color: #f3f3f3;
    }

    .form-field {
        margin-bottom: 15px;
    }

    .error-message p {
        font-size: 14px;
        color: red;
    }

    a:hover {
        color: #ff9800;
    }
</style>
{% endblock %}

Week_4_Django/14-Django/currycrown/management/templates/management/approve_order.html
{% extends 'base.html' %}

{% block title %}Approve Order{% endblock %}

{% block content %}
    <div class="order-header">
        <h1 style="text-align: center; margin-bottom: 3%; font-size: 400%;">Approve Order</h1>
    </div>
    
    <h3 style="text-align: center;">Order Details</h3>
    
    <div class="order-details" style="text-align: center;">
        <table border="1" style="width: 50%; margin: 20px auto; text-align: center;">
            <tr>
                <th>Order ID</th>
                <td>{{ order.order_id }}</td>
            </tr>
            <tr>
                <th>Customer Name</th>
                <td>{{ order.user.username }}</td>
            </tr>
            <tr>
                <th>Order Total</th>
                <td> Rs. {{ order.total_price }}</td>
            </tr>
            <tr>
                <th>Order Time</th>
                <td>{{ order.order_time }}</td>
            </tr>
            <tr>
                <th>Order Status</th>
                <td>{{ order.order_status }}</td>
            </tr>
        </table>
    </div>

    <div class="update-status-form" style="text-align: center; margin-top: 30px;">
        <form method="POST">
            {% csrf_token %}
            
            <label for="Updated status" style="font-size: 18px; font-weight: bold; color: #333; margin-right: 10px;">Select New Status:</label>
            
            <select name="Updated status" id="Updated status" style="padding: 8px 12px; font-size: 14px; background-color: #f0f0f0; border: 2px solid #ff9800; color: #333; border-radius: 5px; text-align: center; width: 160px; display: inline-block; margin-left: 10px; transition: all 0.3s;">
                <option value="pending" {% if order.order_status == "pending" %}selected{% endif %}>Pending</option>
                <option value="complete" {% if order.order_status == "completed" %}selected{% endif %}>Completed</option>
                <option value="cancelled" {% if order.order_status == "Cancelled" %}selected{% endif %}>Cancelled</option>
            </select>
            
            <br><br>
            <button type="submit" style="width: 20%; padding: 10px 20px; background-color: #ffbe33; border: none; color: white; border-radius: 5px; text-transform: uppercase; transition: all 0.3s;">Update Status</button>
            <br><br>
            <a href="{% url 'management:show_orders' %}" style="text-decoration: none; color: #4CAF50; font-weight: bold;">Go back to orders</a>
        </form>
    </div>

    <br>
{% endblock %}

Week_4_Django/14-Django/currycrown/management/templates/management/remove_menu_item.html
{% extends 'base.html' %}

{% block title %}Confirm Deletion{% endblock %}

{% block content %}
    <div class="content-container" style="max-width: 800px; margin: auto; padding: 20px;">
        <!-- Main Title -->
        <h1 style="text-align: center; font-size: 3.5rem; margin-bottom: 20px; color: #333;">Delete Item</h1>
        
        <!-- Subheading -->
        <h3 style="text-align: center; font-size: 1.75rem; margin-bottom: 20px; color: #666;">Are you sure you want to delete this item?</h3>
        
        <!-- Item Details Section -->
        <div class="item-details" style="text-align: center; margin-bottom: 30px;">
            <p style="font-size: 1.25rem; margin-bottom: 10px;"><strong>{{ item.item_name }}</strong></p>
            <img src="{{ item.item_image.url }}" alt="{{ item.item_name }}" style="width: 300px; height: 200px; object-fit: cover; border-radius: 8px; margin-bottom: 15px;">
            
            <p style="font-size: 1.1rem; margin-bottom: 5px;"><strong>Price:</strong> Rs. {{ item.item_price }}</p>
        </div>
        
        <!-- Action Buttons Section -->
        <div class="button-container" style="text-align: center; margin-bottom: 3%;">
            <!-- Delete Button -->
            <form method="POST" style="display: inline-block; ">
                {% csrf_token %}
                <button type="submit" class="submit-button" 
                        style="background-color: #f44336; color: white; font-size: 1.2rem; padding: 12px 30px; border: none; border-radius: 5px; cursor: pointer; 
                               transition: background-color 0.3s ease; width: 20%;">
                     Delete
                </button>
            </form>
            
            <!-- Cancel Link -->
            <a href="{% url 'management:view_menu' %}" class="cancel-link" 
               style="margin-left: 18px; font-size: 1.2rem; color: #007bff; text-decoration: none; 
                      transition: color 0.3s ease; cursor: pointer; text-align: center;">
                Cancel
            </a>
        </div>
    </div>
{% endblock %}

Week_4_Django/14-Django/currycrown/management/templates/management/show_orders.html
{% extends 'base.html' %}

{% block title %}Order Status{% endblock %}

{% block content %}
    <!-- Styled Title -->
    <h1 style="text-align: center; margin-bottom: 3%; font-size: 400%;">Order Status</h1>


    <form method="post">
        {% csrf_token %}
        
        <!-- Styled buttons with inline styles for colors and spacing -->
        <div class="button-container" style="text-align: center; margin-bottom: 20px;">
            <button name="specific" type="submit" value="" style="max-width: 250px; height: 50px; padding: 10px 20px; background-color: #336dff; border: none; color: white; border-radius: 5px; margin: 0 10px; text-transform: uppercase; transition: all 0.3s; display: inline-flex; justify-content: center; align-items: center; white-space: nowrap;">Show All</button>
            <button name="specific" type="submit" value="complete" style="max-width: 250px; height: 50px; padding: 10px 20px; background-color: #4CAF50; border: none; color: white; border-radius: 5px; margin: 0 10px; text-transform: uppercase; transition: all 0.3s; display: inline-flex; justify-content: center; align-items: center; white-space: nowrap;">Show Completed</button>
            <button name="specific" type="submit" value="pending" style="max-width: 250px; height: 50px; padding: 10px 20px; background-color: #e09930; border: none; color: white; border-radius: 5px; margin: 0 10px; text-transform: uppercase; transition: all 0.3s; display: inline-flex; justify-content: center; align-items: center; white-space: nowrap;">Show Pending</button>
            <button name="specific" type="submit" value="cancelled" style="max-width: 250px; height: 50px; padding: 10px 20px; background-color: #f44336; border: none; color: white; border-radius: 5px; margin: 0 10px; text-transform: uppercase; transition: all 0.3s; display: inline-flex; justify-content: center; align-items: center; white-space: nowrap;">Show Cancelled</button>
        </div>
        

        <br>
        <br>

        <table border="1" style="text-align:center;">
            <thead>
                <tr>
                    <th>Order ID</th>
                    <th>Order Details</th>
                    <th>Customer Name</th>
                    <th>Order Total</th>
                    <th>Order Time</th>
                    <th>Order Status</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                {% for order in orders %}
                <tr>
                    <td>{{ order.order_id }}</td>
                    <td>
                        <ul style="text-align: left;">
                            {% for item in order.order_details %}
                                <li style="margin-left: 10%;">{{ item.item_name }} - {{ item.quantity }}</li>
                            {% empty %}
                                <li>No items available.</li>
                            {% endfor %}
                        </ul>
                    </td>
                    <td>{{ order.user.username }}</td>            
                    <td>Rs. {{ order.total_price }}</td>
                    <td>{{ order.order_time }}</td>
                    {% if order.order_status == "complete" %}
                    <td style="color: green;"><strong>{{ order.order_status }}</strong></td>
                    {% elif order.order_status == 'pending' %}
                    <td style="color: rgb(172, 113, 18);"><strong>{{ order.order_status }}</strong></td>
                    {% elif order.order_status == 'cancelled' %}
                    <td style="color: rgb(213, 58, 37);"><strong>{{ order.order_status }}</strong></td>
                    {%else%}
                    <td><strong>{{ order.order_status }}</strong></td>
                    {% endif %}
                    <td>
                        <a href="{% url 'management:approve_order' order.order_id %}" style="padding: 10px 20px; background-color: #ffbe33; border: none; color: black; border-radius: 5px;  transition: all 0.3s; display: inline-block; text-decoration: none;">Approve</a>
                    </td>
                </tr>
                {% empty %}
                <tr>
                    <td colspan="7">No orders available.</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>

        <br>
    </form>
    <div style="margin-left: auto; margin-right: auto; max-width: 50%; text-align: center; margin-bottom: 3%;">
        <a href="{% url 'landing_page' %}">
            <button  class="add-item-btn">Back to Menu</button> 
        </a>
        </div>
{% endblock %}

Week_4_Django/14-Django/currycrown/management/templates/management/view_menu.html
{% extends 'base.html' %}

{% block title %}View Menu{% endblock %}

{% block content %}
    <div class="menu-header">
        <h1 style="text-align: center; margin-bottom: 3%; font-size: 400%;">Menu</h1>
    </div>

    <div class="menu-actions" style="text-align: center; margin-bottom: 20px;">
    </div>

    <div class="menu-table">
        <table border="1" style="width: 90%; margin: auto; text-align: center;">
            <thead>
                <tr>
                    <th>Item Name</th>
                    <th>Price</th>
                    <th>Description</th>
                    <th>Rating</th>
                    <th>Image</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                
                {% for item in menu_items %}
                    <tr>
                        <td>{{ item.item_name }}</td>
                        <td>Rs. {{ item.item_price }}</td>
                        <td>{{ item.item_desc }}</td>
                        <td>{{ item.item_rating }}</td>
                        <td>
                            <img src="{{ item.item_image.url }}" alt="{{ item.item_name }}" width="250" height="200">
                        </td>
                        <td>
                            <!-- Update Button -->
                            <a href="{% url 'management:update_menu' item.item_id %}">
                                <button class="update-btn">Update</button>
                            </a>
                            <br>
                            <!-- Remove Button -->
                            <a href="{% url 'management:remove_menu_item' item.item_id %}">
                                <button class="remove-btn">Remove</button>
                            </a>
                        </td>
                    </tr>
                {% empty %}
                    <tr>
                        <td colspan="6">No menu items available.</td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <br>
        <!-- Add New Item Button -->
        <div style="margin-left: auto; margin-right: auto; max-width: 50%; text-align: center">
            <div class="pagination" style="margin-left: 43%; margin-bottom: 5%;">
                <span class="step-links">
                    {% if menu_items.has_previous %}
                            <a href="?page={{ menu_items.previous_page_number }}">previous</a>
                    {% endif %}

                    <span class="current">
                        Page {{ menu_items.number }} of {{ menu_items.paginator.num_pages }}.
                    </span>
    
                    {% if menu_items.has_next %}
                        <a href="?page={{ menu_items.next_page_number }}">next</a>
                    {% endif %}
                </span>
            </div>
        <a href="{% url 'management:add_menu_item' %}">
            <button  class="add-item-btn">Add New Item</button> 
        </a>
        </div>
        <br>
    </div>
{% endblock %}