Week_4_Django/14-Django/poll/authentication/urls.py
from django.urls import path
from .views import CustomLoginView, SignUpView, CustomLogoutView

urlpatterns = [
    path("login/", CustomLoginView.as_view(), name="login"),
    path("signup/", SignUpView.as_view(), name="signup"),
    path("logout/", CustomLogoutView.as_view(), name="logout"),
]

Week_4_Django/14-Django/poll/greeting/urls.py
from django.urls import path
from .views import PollListView, PollDetailView, VoteFormView, UploadFileView

app_name = "polls"

urlpatterns = [
    path("", PollListView.as_view(), name="poll_list"),
    path("poll/<int:pk>/", PollDetailView.as_view(), name="poll_detail"),
    path("poll/<int:poll_id>/vote/", VoteFormView.as_view(), name="vote_form"),
    path("upload_excel/", UploadFileView.as_view(), name="excel_upload"),
]

Week_4_Django/14-Django/poll/poll/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("greeting/", include("greeting.urls")),
    path("", include("authentication.urls")),
]

Week_4_Django/14-Django/poll/greeting/models.py
from django.db import models
from datetime import timedelta, timezone
from django.contrib.auth.models import User


class PollManager(models.Manager):
    def active(self):
        return self.filter(is_active=True)

    def created_within_last_week(self):
        one_week_ago = timezone.now() - timedelta(days=7)
        return self.filter(created_at__gte=one_week_ago)


class VoteManager(models.Manager):
    def for_poll(self, poll):
        return self.filter(poll=poll)


class Poll(models.Model):
    question_text = models.CharField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.question_text


class Vote(models.Model):
    poll = models.ForeignKey(Poll, related_name="votes", on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Vote for {self.poll.question_text} from {self.user}"

Week_4_Django/14-Django/poll/authentication/forms.py
# forms.py
from django import forms
from django.contrib.auth.models import User


class CustomUserCreationForm(forms.ModelForm):
    password1 = forms.CharField(widget=forms.PasswordInput)
    password2 = forms.CharField(widget=forms.PasswordInput)

    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30, required=True)
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = (
            "username",
            "first_name",
            "last_name",
            "email",
            "password1",
            "password2",
        )

    def clean_password2(self):

        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")

        if password1 and password2 and password1 != password2:
            raise forms.ValidationError("Passwords do not match")

        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password1"])

        if commit:
            user.save()
        return user

Week_4_Django/14-Django/poll/greeting/forms.py
from django import forms
from django.core.exceptions import ValidationError
from .models import Vote


class VoteForm(forms.ModelForm):
    class Meta:
        model = Vote
        fields = ["poll", "user"]


class UploadExcelForm(forms.Form):
    file = forms.FileField()

    def clean_file(self):
        file = self.cleaned_data.get("file")
        if file.size > 10 * 1024 * 1024:  # size to be 10MB
            raise ValidationError("File size must be under 10 MB.")

        if not file.name.endswith(".xlsx"):  # should be xlsx file
            raise ValidationError("Only .xlsx files are allowed.")

Week_4_Django/14-Django/poll/authentication/views.py
from django.contrib.auth.views import LoginView, LogoutView
from django.views.generic import FormView
from django.urls import reverse_lazy
from .forms import CustomUserCreationForm
from django.contrib.auth.mixins import LoginRequiredMixin


class CustomLoginView(LoginView):
    template_name = "auth/login.html"


class SignUpView(FormView):
    template_name = "auth/signup.html"
    form_class = CustomUserCreationForm
    success_url = reverse_lazy("login")  # Redirect to login after successful signup

    def form_valid(self, form):
        form.save()
        return super().form_valid(form)


class CustomLogoutView(LogoutView):
    next_page = "/"

Week_4_Django/14-Django/poll/greeting/views.py
from django.views.generic import View, ListView, DetailView
from django.views.generic.edit import FormView
from django.urls import reverse_lazy
from django.shortcuts import render
from django.http import HttpResponseForbidden
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect
from .models import Poll, Vote
import logging
from .forms import VoteForm, UploadExcelForm
import openpyxl


class PollListView(LoginRequiredMixin, ListView):
    model = Poll
    template_name = "poll_list.html"
    context_object_name = "polls"
    login_url = "/login"


class PollDetailView(DetailView):
    model = Poll
    template_name = "poll_detail.html"
    context_object_name = "poll"

    def post(self, request):
        return redirect("greeting:vote_from")


logger = logging.getLogger("user_actions")


class VoteFormView(FormView):
    template_name = "vote_form.html"
    form_class = VoteForm
    success_url = reverse_lazy("polls:poll_list")

    def form_valid(self, form):
        poll = form.cleaned_data["poll"]
        username = form.cleaned_data["user"]
        if Vote.objects.filter(poll=poll, user=username).exists():
            return HttpResponseForbidden("You have already voted for poll.")

        Vote.objects.create(poll=poll, user=username)
        logger.info(f"User  {username} voted for: {poll}")
        return super().form_valid(form)


class UploadFileView(View):

    def get(self, request):
        form = UploadExcelForm()
        return render(request, "upload_excel.html", {"form": form})

    def post(self, request):
        form = UploadExcelForm(request.POST, request.FILES)
        if form.is_valid():
            workbook = openpyxl.load_workbook(
                filename=request.FILES["file"], data_only=True
            )
            sheet = workbook.active
            data = []
            for row in sheet.iter_rows(values_only=True):
                question = row
                Poll.objects.create(question_text=question)
                data.append(row)
            return render(request, "display_data.html", {"data": data})

        return render(request, "upload_excel.html", {"form": form})


# def active_polls_view(request):
#     active_polls = Poll.objects.active()  # Use the custom manager method
#     return render(request, "active_polls.html", {"polls": active_polls})


# def recent_polls_view(request):

#     recent_polls = (
#         Poll.objects.created_within_last_week()
#     )  # Use the custom manager method
#     return render(request, "recent_polls.html", {"polls": recent_polls})


# def votes_for_poll_view(request, poll_id):
#     poll = Poll.objects.get(id=poll_id)
#     votes = Vote.objects.for_poll(poll)  # Use the custom manager method
#     return render(request, "votes_for_poll.html", {"poll": poll, "votes": votes})

Week_4_Django/14-Django/poll/greeting/templates/display_data.html
<!DOCTYPE html>
<html>
<head>
    <title>Upload Success</title>
</head>
<body>
    <h1>File Uploaded Successfully</h1>
    <h2>Data:</h2>
    <table border="1">
        <thead>
            <tr>
                {% for header in data.0 %}
                    <th>{{ header }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for row in data|slice:"1:" %}  
                <tr>
                    {% for cell in row %}
                        <td>{{ cell }}</td>
                    {% endfor %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
</body>
</html>

Week_4_Django/14-Django/poll/greeting/templates/poll_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ poll.question_text }}</title>
</head>
<body>
    <h1>{{ poll.question_text }}</h1>
    <p>Created at: {{ poll.created_at }}</p>
    <p>Status: {% if poll.is_active %} Active {% else %} Closed {% endif %}</p>

    <h2>Submit Your Vote</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <a href="{% url 'polls:vote_form' poll.pk %}">Submit a vote</a>
    </form>
</body>
</html>

Week_4_Django/14-Django/poll/greeting/templates/poll_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Poll List</title>
</head>
<body>
    <h1>Poll Questions</h1>
    
    <ul>
        {% for poll in polls %}
            <li>
                <a href="{% url 'polls:poll_detail' poll.pk %}">{{ poll.question_text }}</a>
            </li>
        {% endfor %}
    </ul>
   
    
</body>
</html>

Week_4_Django/14-Django/poll/greeting/templates/upload_excel.html
<!DOCTYPE html>
<html>
<head>
    <title>Upload Excel File</title>
</head>
<body>
    <h1>Upload Excel File</h1>
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {% for field in form %}
        {{field}}
        {% endfor %}
        <br>
        <br>
        <button type="submit">Upload</button>
    </form>
    {% if form.errors %}
        <div style="color: red;">
            <h3>Errors:</h3>
            <ul>
                {% for errors in form.errors.items %}
                    <li>{{ field }}: {{ errors|join:", " }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
</body>

</html>

Week_4_Django/14-Django/poll/greeting/templates/vote_form.html
<!DOCTYPE html>
<html>
<head>
    <title>Vote for Poll</title>
</head>
<body>
    <h1>Vote for Poll: {{ poll.question_text }}</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Submit Vote</button>
    </form>
</body>
</html>