Week_4_Django/14-Django/currycrown/currycrown/urls.py
# from django.contrib import views as auth_views
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf import settings
from django.conf.urls.static import static
from django.views.generic.base import RedirectView
from . import views
from debug_toolbar.toolbar import debug_toolbar_urls
from django.shortcuts import redirect

urlpatterns = [
    path("admin/", admin.site.urls),
    path("logout", views.user_logout, name="logout"),
    path("management/", include("management.urls")),
    path("customer/", include("customer.urls")),
    path("register/", views.register, name="register_user"),
    path("login/", views.user_login, name="login"),
    path("", views.about, name="landing_page"),
    re_path(r"^.*$", lambda request: redirect("landing_page")),
] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Week_4_Django/14-Django/currycrown/customer/urls.py
from django.urls import path
from . import views

app_name = "customer"

urlpatterns = [
    path("view/", views.view_menu, name="view_menu"),
    path("place_order/", views.place_order, name="place_order"),
    path(
        "order_confirmation/<int:order_id>/",
        views.order_confirmation,
        name="order_confirmation",
    ),
    path("show_order/<int:user_id>/", views.view_orders, name="show_orders"),
]

Week_4_Django/14-Django/currycrown/management/urls.py
from django.urls import path
from . import views

app_name = "management"  

urlpatterns = []

menu_task = [
    path("add/", views.add_menu_item, name="add_menu_item"),
    path("view/", views.view_menu, name="view_menu"),
    path("specificmenu/", views.specific_view_menu, name="specific_view_menu"),
    path("remove/<int:item_id>/", views.remove_menu_item, name="remove_menu_item"),
    path("update/<int:item_id>/", views.update_menu, name="update_menu"),
]

order_task = [
    path("order/", views.show_orders, name="show_orders"),
    path("order/approve/<int:order_id>/", views.approve_order, name="approve_order"),
]
urlpatterns = urlpatterns + menu_task + order_task

Week_4_Django/14-Django/currycrown/currycrown/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("first_name", "last_name", "email", "username")
        widgets = {
            "first_name": forms.TextInput(
                attrs={
                    "placeholder": "First Name",
                }
            ),
            "last_name": forms.TextInput(
                attrs={
                    "placeholder": "Last Name",
                }
            ),
            "email": forms.EmailInput(
                attrs={
                    "placeholder": "Email Address",
                }
            ),
            "username": forms.TextInput(
                attrs={
                    "placeholder": "Username",
                }
            ),
        }

    def clean_email(self):
        email = self.cleaned_data.get("email")
        if User.objects.filter(email=email).exists():
            raise ValidationError("This email address is already taken.")
        return email

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        # Setting placeholder for password1 and password2 explicitly
        self.fields["password1"].widget.attrs.update(
            {
                "placeholder": "Enter Password",
            }
        )
        self.fields["password2"].widget.attrs.update(
            {
                "placeholder": "Confirm Password",
            }
        )

Week_4_Django/14-Django/currycrown/currycrown/views.py
from django.shortcuts import render, redirect, reverse
from management.models import Menu
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import AuthenticationForm
from .forms import CustomUserCreationForm
from django.contrib.auth import logout


def about(request):
    return render(request, "about.html")


def user_logout(request):
    logout(request)
    return redirect("landing_page")


def user_login(request):
    if request.method == "POST":
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if user.is_staff:
                return redirect("landing_page")
            else:
                return redirect("customer:view_menu")
        else:
            return render(request, "registration/login.html", {"form": form})
    if request.user.is_authenticated:
        return redirect("landing_page")
    form = AuthenticationForm()
    return render(request, "registration/login.html", {"form": form})


def register(request):
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("login")
    else:
        form = CustomUserCreationForm()
    return render(request, "registration/register.html", {"form": form})

Week_4_Django/14-Django/currycrown/currycrown/templates/about.html
<!DOCTYPE html>
<html>

<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <link rel="shortcut icon" href="static/images/favicon.png" type="">

  <title> CurryCrown </title>

  <!-- bootstrap core css -->
  <link rel="stylesheet" type="text/css" href="static/css/bootstrap.css" />

  <!--owl slider stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  <!-- nice select  -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==" crossorigin="anonymous" />
  <!-- font awesome style -->
  <link href="static/css/font-awesome.min.css" rel="stylesheet" />

  <!-- Custom styles for this template -->
  <link href="static/css/style.css" rel="stylesheet" />
  <!-- responsive style -->
  <link href="static/css/responsive.css" rel="stylesheet" />

</head>

<body>

  <div class="hero_area">
    <div class="bg-box">
      <img src="static/images/hero-bg.jpg" alt="">
    </div>
    <!-- header section strats -->
    <header class="header_section">
      {% include 'header.html' %}
    </header>
    <!-- end header section -->
    <!-- slider section -->
    <section class="slider_section ">
      <div id="customCarousel1" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">
          <div class="carousel-item active">
            <div class="container ">
              <div class="row">
                <div class="col-md-7 col-lg-6 ">
                  <div class="detail-box">
                    <h1>
                      CurryCrown Restaurant
                    </h1>
                    <p>
                      At Currycrown Restaurant, we serve authentic, flavorful curries with a modern twist. From rich, aromatic curries to sizzling appetizers, every dish is crafted with the finest ingredients. Whether you're craving classic Butter Chicken or a fiery buVindaloorger, each bite is a burst of flavor.                    <div class="btn-box">
                      {% if not user.is_authenticated or not user.is_staff %}
                      <a href="{% url 'customer:view_menu' %}" class="btn1">
                        View Menu
                      {% else %}
                      <a href="{% url 'management:show_orders' %}" class="btn1">
                        Approve Orders
                      </a>
                      <br>
                      <a href="{% url 'management:view_menu' %}" class="btn1">
                        Edit Menu
                      {%endif%}
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          

    </section>
    <!-- end slider section -->
  </div>


  <!-- footer section -->
  <footer class="footer_section">
    {% include 'footer.html' %}
  </footer>
  <!-- footer section -->

  <!-- jQery -->
  <script src="static/js/jquery-3.4.1.min.js"></script>
  <!-- popper js -->
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
  </script>
  <!-- bootstrap js -->
  <script src="static/js/bootstrap.js"></script>
  <!-- owl slider -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/owl.carousel.min.js">
  </script>
  <!-- isotope js -->
  <script src="https://unpkg.com/isotope-layout@3.0.4/dist/isotope.pkgd.min.js"></script>
  <!-- nice select -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/js/jquery.nice-select.min.js"></script>
  <!-- custom js -->
  <script src="static/js/custom.js"></script>
  <!-- Google Map -->
  <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCh39n5U-4IoWpsVGUHWdqB6puEkhRLdmI&callback=myMap">
  </script>
  <!-- End Google Map -->

</body>

</html>

Week_4_Django/14-Django/currycrown/currycrown/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  
  <!-- Mobile Metas -->
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
  
  <!-- Site Metas -->
  <meta name="keywords" content="" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  
  <link rel="shortcut icon" href="{% static 'images/favicon.png' %}" type="">

  <title>CurryCrown</title>

  <!-- Bootstrap core CSS -->
  <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.css' %}" />
  
  <!-- Owl carousel stylesheet -->
  <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/OwlCarousel2/2.3.4/assets/owl.carousel.min.css" />
  
  <!-- Nice select -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-nice-select/1.1.0/css/nice-select.min.css" integrity="sha512-CruCP+TD3yXzlvvijET8wV5WxxEh5H8P4cmz0RFbKK6FlZ2sYl3AEsKlLPHbniXKSrDdFewhbmBK5skbdsASbQ==" crossorigin="anonymous" />
  
  <!-- Font Awesome style -->
  <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet" />
  
  <!-- Custom styles for this template -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" />
  
  <!-- Responsive style -->
  <link href="{% static 'css/responsive.css' %}" rel="stylesheet" />
  
  <!-- Additional custom styles (if any) -->
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
  
  <title>{% block title %}Login{% endblock %}</title>
</head>

<body>
  <!-- Header Section -->
  <header class="header_section">
    {% include 'header.html' %}
  </header>

  <!-- Content Section (dynamic content will be inserted here) -->
  {% block content %}
  {% endblock %}

  <!-- Footer Section -->
  <footer class="footer_section">
    {% include 'footer.html' %}
  </footer>

</body>
</html>

Week_4_Django/14-Django/currycrown/currycrown/templates/footer.html
    <!-- footer section -->
    <footer class="footer_section">
        <div class="container">
            <div class="row">
                <div class="col-md-4 footer-col">
                    <h4>Contact Us</h4>
                    <p><i class="fa fa-map-marker" aria-hidden="true"></i> 27, Hudson Lane, Noida</p>
                    <p><i class="fa fa-phone" aria-hidden="true"></i> Call +01 1234567890</p>
                    <p><i class="fa fa-envelope" aria-hidden="true"></i> info@CurryCrown.com</p>
                </div>
                <div class="col-md-4 footer-col">
                    <a class="footer-logo">CurryCrown</a>
                    <p>Best Restaurant To Ever Exist</p>
                </div>
                <div class="col-md-4 footer-col">
                    <h4>Opening Hours</h4>
                    <p>Everyday</p>
                    <p>10.00 Am -10.00 Pm</p>
                </div>
            </div>
            <div class="footer-info">
            </div>
        </div>
    </footer>

    <!-- JavaScript Files -->
</body>
</html>

Week_4_Django/14-Django/currycrown/currycrown/templates/header.html
{% load static %}
<div class="container">
    <nav class="navbar navbar-expand-lg custom_nav-container ">
      <a class="navbar-brand">
        <span class="icon">
          <img src="/static/images/crown.png" alt="Crown Icon" style="width: 40px; height: 40px; transform: rotate(-30deg); margin-bottom: 65px; margin-right: -28px;">        
        </span>
        <span>
          CurryCrown
        </span>
      </a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class=""> </span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav  mx-auto ">
          <li class="nav-item active">
            <a class="nav-link" href="{% url 'landing_page' %}">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            {% if not user.is_authenticated or not user.is_staff%}
            <a class="nav-link" href="{% url 'customer:view_menu' %}">Menu</a>
            {%else%}
            <a class="nav-link" href="{% url 'management:view_menu' %}">Menu</a>
            {% endif %}
          </li>
          <li class="nav-item">
            {% if not user.is_authenticated or not user.is_staff%}
            <a class="nav-link" href="{% url 'customer:place_order' %}">Order</a>
            {%else%}
            <a class="nav-link" href="{% url 'management:show_orders' %}">Order</a>
            {% endif %}
          </li>
        </ul>
        <div class="user_option">
          </form>
          {% if not user.is_authenticated %}
            <a href="{% url 'login' %}", class="order_online">
              Login
          {% elif  user.is_authenticated %}
              {%if not user.is_staff %}
                <a href="{% url 'customer:show_orders' user.id%}" class="user_link">
                  <i class="fa fa-user" aria-hidden="true"></i>
                </a>              
              {% elif user.is_staff %}
                <a href="{% url 'management:show_orders'%}" class="user_link">
                  <i class="fa fa-user" aria-hidden="true"></i>
                </a>
              {% endif %}
            <a href="{%url 'logout' %}", class="order_online">
              Logout
          {% endif %}
          </a>
        </div>
      </div>
    </nav>
  </div>